### ISSUE TITLE
IsIterableWithDistinctElements is quadratic

### ISSUE THREAD

**Issue by TWiStErRob** [cirneco/cirneco#6]
Consider the following change:

``` java
@Override
public void describeMismatchSafely(final Iterable<? extends E> actual, final Description mismatchDescription) {
    final Set<E> elements = new HashSet<>();
    final Collection<E> nonDistinctElements = new ArrayList<>();

    for(E element : actual) {
        if (!elements.add(element)) {
            nonDistinctElements.add(element);
        }
    }
    ...
}
```

Before:
- `listCopy` (`n` operations: copies each item)
- `HashSet(copied)` (`n` operations: hashes each item)
- `for` loop: (over `n` items)
  - `Collections.frequency` (`n` `equals`s: to get the frequency)
  - one `add` with hashing

Overall complexity: `n + n + n*(n+1) = O(n^2)`

After:
- `for` loop: (over `n` items)
  - one hashing
  - one `add` without hashing

Overall complexity: `n*(1+1) = O(n)`

---

Same trick can be used to `matchesSafely`:

``` java
@Override
public boolean matchesSafely(final Iterable<? extends E> actual) {
    final Set<E> elements = new HashSet<>();
    for (E element : actual) {
        if (!elements.add(element)) {
            return false;
        }
    }
    return true;
}
```

Complexity doesn't change, but instead of the best case `3*n` operations, it is reduced to best case `2` and worst case `1*n`.

**Comment by robertotru** [comment]
Hey
Thanks for the tips. I encourage you to open a pull request with the proposed changes. I will create a minor release afterwards.
How it sounds to you?
Best
Roberto

**Comment by TWiStErRob** [comment]
Just got around to this, do you still want a PR, or you started work on it?

**Comment by robertotru** [comment]
I prefer a PR so that it remains that was coming from you...

**Comment by TWiStErRob** [comment]
Tip: you can set author for any commit manually: http://stackoverflow.com/q/11579311/253468
I've done it previously: https://github.com/bumptech/glide/pull/1092

**Comment by robertotru** [comment]
Changes have been merged, thanks for the PR. 
The minor version will be released in a few days.

**Comment by TWiStErRob** [comment]
No need to do it unless you want to. I'm not using this lib.

**Comment by robertotru** [comment]
It costed me 5 minutes, just the time to run a script. 
Thanks for the changes.
